- name: welcome-new-contributors
  # You may pin to the exact commit or the version.
  # uses: garg3133/welcome-new-contributors@a38583ed8282e23d63d7bf919ca2d9fb95300ca6
  uses: garg3133/welcome-new-contributors@v1.2
  with:
    # The GITHUB_TOKEN to access your repository or OAUTH_TOKEN to use your bot github account.
    token: 
    # Is the token provided above an OAUTH_TOKEN? (Bot account should be a collaborator on your repo.)
    is-oauth-token: # optional
    # Welcome message for new issue.
    issue-message: # optional
    # Welcome message for new issue.
    pr-message: # optional
